name: hchat
version: 0.1.0.0
github: "danielsanrocha/hchat"
license: BSD3
author: "Daniel Santana Rocha"
maintainer: "danielsantanarocha@gmail.com"
copyright: "2020 Author Daniel SantanaRocha"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/danielsanrocha/hchat#readme>

dependencies:
  - base >= 4.7 && < 5
  - scotty == 0.12
  - text == 1.2.4.0
  - aeson == 1.5.4.1

library:
  source-dirs: src

executables:
  hchat-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hchat

tests:
  hchat-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hchat
